version: "3.10"
services:
  back:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8002
    expose: [8001]
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=q1726354
      - POSTGRES_DB=app
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: