# Generated by Django 4.1 on 2022-08-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=255, unique=True, verbose_name='Название')),
                ('price', models.FloatField(default=500, help_text='Обязательное поле', max_length=255, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='Empty', max_length=255, verbose_name='Описание')),
                ('type', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductAmounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Обязательное поле', verbose_name='Количество')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.product')),
            ],
            options={
                'verbose_name': 'Количество продукта',
                'verbose_name_plural': 'Количества продуктов',
            },
        ),
    ]
