# Generated by Django 4.1 on 2022-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Оплачено'), (1, 'Ожидание'), (2, 'Отмена')], default=1),
        ),
    ]
