# Generated by Django 4.1 on 2022-08-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
            },
        ),
        migrations.RenameField(
            model_name='productamounts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(help_text='Обязательное поле', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='petstore.producttype'),
        ),
    ]
