# Generated by Django 4.1 on 2022-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0004_remove_order_id_remove_productamounts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='petstore.product'),
        ),
    ]
