# Generated by Django 4.1 on 2022-11-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_newsletter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получать рассылку'), (2, 'Не получать рассылку')], default=1),
        ),
    ]
