# Generated by Django 4.1 on 2022-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Клиент'), (1, 'Менеджер'), (2, 'Админ')], default=0),
        ),
    ]
