# Generated by Django 4.1 on 2022-10-02 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referaluser_userfrom', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший пользователь')),
                ('user_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referaluser_userto', to=settings.AUTH_USER_MODEL, verbose_name='приглашенный пользователь')),
            ],
            options={
                'verbose_name': 'Реферальные клиенты',
            },
        ),
    ]
