services:
  back:
    build: .
    command: gunicorn --bind 0.0.0.0:8003 app.asgi -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 8000:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=q1726354
      - POSTGRES_DB=app
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.19.0-alpine
    build: ./nginx
    ports:
      - 80:80
      - 443:80
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    depends_on:
      - back
volumes:
  postgres_data:
  static_volume:
  media_volume: